'use strict';
const $=id=>document.getElementById(id);
let db, state={version:1,notes:[],folders:[],settings:{theme:'light',font:16,mode:'split'}}, current=null, dirty=false, saving=false, revision=0, saveTimer, previewTimer, urls=[], ready=false;
const uid=()=>Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,10);
const safeName=s=>{let value=String(s).replace(/[<>:"/\\|?*\x00-\x1f]/g,'_').replace(/[. ]+$/,'').trim().slice(0,100)||'Без названия';if(/^(con|prn|aux|nul|com[1-9]|lpt[1-9])(?:\.|$)/i.test(value))value='_'+value;return value};
const escapeHtml=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const note=()=>state.notes.find(n=>n.id===current);
const path=n=>(n.folder?n.folder+'/':'')+n.title;
const live=()=>state.notes.filter(n=>!n.deleted);
function toast(s){$('toast').textContent=s;$('toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').style.display='none',6500)}
function storageError(e){dirty=true;$('status').textContent='Не сохранено! Скачайте резервную копию. '+(e&&e.name||'Ошибка хранилища');$('status').classList.add('error');toast('Не удалось сохранить. Не закрывайте страницу; используйте «Экспорт».')}
function tx(store,mode,operation){return new Promise((resolve,reject)=>{if(!db)return reject(new Error('Хранилище недоступно'));const t=db.transaction(store,mode),req=operation(t.objectStore(store));let result;req.onsuccess=()=>result=req.result;t.oncomplete=()=>resolve(result);t.onerror=()=>reject(t.error);t.onabort=()=>reject(t.error||new Error('Запись прервана'))})}
async function persist(){if(saving)return;clearTimeout(saveTimer);saving=true;const rev=revision;try{await tx('state','readwrite',s=>s.put(state,'vault'));if(rev===revision){dirty=false;$('status').textContent='Сохранено в браузере';$('status').classList.remove('error')}}catch(e){storageError(e)}finally{saving=false;if(dirty&&rev!==revision)saveTimer=setTimeout(persist,150)}}
function changed(){dirty=true;revision++;$('status').textContent='Сохранение…';saveTimer=setTimeout(persist,350)}
function wikiRefs(text){return Array.from(text.matchAll(/\[\[([^\]\n]+)\]\]/g),m=>m[1].split('|')[0].trim())}
function resolve(target,from){target=target.replace(/\.md$/i,'');if(target.includes('/'))return live().filter(n=>path(n)===target.replace(/^\//,''));return live().filter(n=>n.title===target)}
function makeNote(title,folder='',text=''){const n={id:uid(),title:safeName(title),folder,text,tags:[],favorite:false,modified:Date.now(),deleted:false};state.notes.push(n);return n}
function showDialog(title,html){$('dialogBody').innerHTML='<h2>'+escapeHtml(title)+'</h2>'+html;$('dialog').showModal()}
$('closeDialog').onclick=()=>$('dialog').close();
function renderList(){const q=$('search').value.toLowerCase(),tag=$('tagFilter').value.toLowerCase().replace(/^#/,''),f=$('filter').value,folder=$('folderFilter').value;const list=state.notes.filter(n=>(f==='trash'?n.deleted:!n.deleted)&&(f!=='favorite'||n.favorite)&&(!folder||n.folder===folder)&&(!tag||n.tags.some(t=>t.toLowerCase().includes(tag)))&&((n.title+' '+n.text).toLowerCase().includes(q))).sort((a,b)=>$('sort').value==='title'?a.title.localeCompare(b.title,'ru'):b.modified-a.modified);$('notes').replaceChildren();for(const n of list){const b=document.createElement('button');b.className=n.id===current?'active':'';b.textContent=(n.favorite?'★ ':'')+n.title;const s=document.createElement('small');s.textContent=(n.folder||'Без папки')+(n.tags.length?' · #'+n.tags.join(' #'):'');b.appendChild(s);b.onclick=()=>select(n.id);$('notes').appendChild(b)}$('total').textContent=list.length+' заметок'}
function folders(){for(const id of ['folder','folderFilter']){const el=$(id),v=el.value;el.replaceChildren();const o=document.createElement('option');o.value='';o.textContent=id==='folder'?'Без папки':'Все папки';el.appendChild(o);for(const f of state.folders){const x=document.createElement('option');x.value=f;x.textContent=f;el.appendChild(x)}el.value=v}}
function select(id){current=id;const n=note();$('workspace').hidden=!n;if(!n)return;$('title').value=n.title;$('editor').value=n.text;$('tags').value=n.tags.join(', ');$('folder').value=n.folder;$('star').textContent=n.favorite?'★':'☆';$('delete').textContent=n.deleted?'Восстановить':'В корзину';for(const el of [$('editor'),$('title'),$('tags'),$('folder'),$('star')])el.disabled=n.deleted;renderList();renderPreview();count();if(dirty)persist()}
function count(){const t=$('editor').value.trim();$('count').textContent=(t?t.split(/\s+/).length:0)+' слов · '+$('editor').value.length+' символов'}
function mode(m){state.settings.mode=m;$('panels').className=m;document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===m));$('toolbar').hidden=m==='view'}
function applySettings(){document.body.classList.toggle('dark',state.settings.theme==='dark');document.documentElement.style.setProperty('--size',state.settings.font+'px');$('font').value=state.settings.font;mode(state.settings.mode)}
function attachmentKey(src,n){try{src=decodeURIComponent(src)}catch{}if(/^attachments\/[a-zA-Z0-9._-]+$/.test(src))return src;if(n.folder&&/^(\.\.\/)+attachments\/[a-zA-Z0-9._-]+$/.test(src))return 'attachments/'+src.split('/').pop();return null}
async function renderPreview(){const n=note();if(!n)return;const token=uid();renderPreview.token=token;urls.forEach(URL.revokeObjectURL);urls=[];
// Encode wiki targets so they cannot introduce HTML attributes or executable links.
const renderer=new marked.Renderer();renderer.html=()=>'';renderer.image=(href,title,text)=>'<img data-source="'+escapeHtml(href||'')+'" alt="'+escapeHtml(text||'')+'">';
let html=marked.parse(n.text,{renderer,gfm:true,breaks:false});
const holder=document.createElement('div');holder.innerHTML=DOMPurify.sanitize(html,{FORBID_TAGS:['style','iframe','object','embed','form','video','audio','svg','math'],FORBID_ATTR:['style','srcset']});
// Wiki links are transformed only in text nodes, never code blocks or raw attributes.
const walker=document.createTreeWalker(holder,NodeFilter.SHOW_TEXT);const nodes=[];while(walker.nextNode())if(!walker.currentNode.parentElement.closest('code,pre,a'))nodes.push(walker.currentNode);
for(const node of nodes){const re=/\[\[([^\]\n]+)\]\]/g;let m,last=0,frag=document.createDocumentFragment(),found=false;while((m=re.exec(node.textContent))){found=true;frag.appendChild(document.createTextNode(node.textContent.slice(last,m.index)));const a=document.createElement('a');a.href='#';a.dataset.wiki=m[1].split('|')[0].trim();a.textContent=m[1].split('|')[1]||a.dataset.wiki;frag.appendChild(a);last=re.lastIndex}if(found){frag.appendChild(document.createTextNode(node.textContent.slice(last)));node.replaceWith(frag)}}
for(const a of holder.querySelectorAll('a:not([data-wiki])')){const href=a.getAttribute('href')||'';if(!/^(https?:|mailto:|#)/i.test(href)){a.removeAttribute('href')}else{a.target='_blank';a.rel='noopener noreferrer'}}
for(const input of holder.querySelectorAll('input')){if(input.type!=='checkbox')input.remove();else input.disabled=true}const images=Array.from(holder.querySelectorAll('img'));for(const img of images){const src=img.getAttribute('data-source')||'',key=attachmentKey(src,n);img.removeAttribute('src');img.loading='lazy';if(key){img.dataset.attachment=key}else if(/^https?:\/\//i.test(src)){const b=document.createElement('button');b.className='external-image';b.textContent='Разрешить внешнее изображение: '+(img.alt||src);b.onclick=()=>{img.src=src;b.replaceWith(img)};img.replaceWith(b)}else{const s=document.createElement('span');s.textContent='[Изображение недоступно: '+(img.alt||src)+']';img.replaceWith(s)}}
if(renderPreview.token!==token)return;$('preview').replaceChildren(...holder.childNodes);$('preview').dataset.title=n.title;
const loadImage=async img=>{try{const blob=await tx('attachments','readonly',s=>s.get(img.dataset.attachment));if(renderPreview.token!==token)return;if(blob){const u=URL.createObjectURL(blob);urls.push(u);img.src=u}else img.alt='Вложение отсутствует: '+img.dataset.attachment}catch{img.alt='Не удалось прочитать вложение'}};
if(window.IntersectionObserver){if(renderPreview.observer)renderPreview.observer.disconnect();const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){observer.unobserve(e.target);loadImage(e.target)}}),{rootMargin:'200px'});renderPreview.observer=observer;$('preview').querySelectorAll('img[data-attachment]').forEach(img=>observer.observe(img))}else for(const img of $('preview').querySelectorAll('img[data-attachment]'))loadImage(img);
$('backlinks').replaceChildren();for(const other of live().filter(x=>x.id!==n.id&&wikiRefs(x.text).some(r=>resolve(r,x).some(y=>y.id===n.id)))){const b=document.createElement('button');b.textContent=path(other);b.onclick=()=>select(other.id);$('backlinks').appendChild(b)}if(!$('backlinks').children.length)$('backlinks').textContent='Пока нет ссылок на эту заметку.'}
$('preview').onclick=e=>{const a=e.target.closest('[data-wiki]');if(!a)return;e.preventDefault();const target=a.dataset.wiki,matches=resolve(target,note());if(matches.length===1)select(matches[0].id);else if(matches.length>1){showDialog('Выберите заметку','<div id="choices"></div>');for(const n of matches){const b=document.createElement('button');b.textContent=path(n);b.onclick=()=>{$('dialog').close();select(n.id)};$('choices').appendChild(b)}}else if(confirm('Заметки «'+target+'» нет. Создать?')){const bits=target.split('/'),title=bits.pop(),folder=bits.join('/');if(folder&&!state.folders.includes(folder))state.folders.push(folder);const n=makeNote(title,folder);folders();changed();select(n.id)}};
function rewriteLinks(n,newTitle,newFolder){const oldPath=path(n);for(const x of state.notes)x.text=x.text.replace(/\[\[([^\]\n]+)\]\]/g,(all,inside)=>{const p=inside.split('|'),target=p[0].trim();const matches=resolve(target,x);if(matches.length===1&&matches[0].id===n.id)return '[['+(newFolder?newFolder+'/':'/')+newTitle+(p.length>1?'|'+p.slice(1).join('|'):'')+']]';return all})}
function rename(){const n=note();if(!n||n.deleted)return;const title=safeName($('title').value),folder=$('folder').value;if(live().some(x=>x.id!==n.id&&x.title===title&&x.folder===folder)){toast('В этой папке уже есть заметка с таким названием.');$('title').value=n.title;$('folder').value=n.folder;return}rewriteLinks(n,title,folder);n.title=title;n.folder=folder;n.modified=Date.now();$('editor').value=n.text;changed();renderList();renderPreview()}
$('title').onchange=rename;$('folder').onchange=rename;
$('editor').oninput=()=>{const n=note();if(!n)return;n.text=$('editor').value;n.modified=Date.now();changed();count();clearTimeout(previewTimer);previewTimer=setTimeout(()=>{renderPreview();renderList()},200)};
$('tags').onchange=()=>{note().tags=Array.from(new Set($('tags').value.split(',').map(s=>s.trim().replace(/^#/, '')).filter(Boolean)));changed();renderList()};
$('star').onclick=()=>{note().favorite=!note().favorite;changed();select(current)};
$('delete').onclick=()=>{const n=note();if(n.deleted){if(live().some(x=>path(x)===path(n)))n.title+=' (восстановлено '+uid()+')';n.deleted=false}else{if(!confirm('Переместить заметку в корзину? Её можно восстановить.'))return;n.deleted=true}changed();select(current)};
$('new').onclick=()=>{const title=prompt('Название новой заметки','Новая заметка');if(title===null)return;const f=$('folderFilter').value;let t=safeName(title);while(live().some(n=>n.title===t&&n.folder===f))t+=' (копия)';const n=makeNote(t,f);changed();select(n.id)};
$('newFolder').onclick=()=>{const value=prompt('Название папки (для вложенных: Работа/Идеи)');if(!value)return;const f=value.split('/').filter(Boolean).map(safeName).join('/');if(!state.folders.includes(f))state.folders.push(f);folders();changed();renderList()};
for(const id of ['search','tagFilter'])$(id).oninput=renderList;for(const id of ['folderFilter','filter','sort'])$(id).onchange=renderList;
$('theme').onclick=()=>{state.settings.theme=state.settings.theme==='dark'?'light':'dark';applySettings();changed()};$('font').onchange=()=>{state.settings.font=Number($('font').value);applySettings();changed()};document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode(b.dataset.mode);changed()});
function insert(text){const e=$('editor');if(!note()||note().deleted)return;const start=e.selectionStart,end=e.selectionEnd;e.setRangeText(text,start,end,'end');e.dispatchEvent(new Event('input'));e.focus()}
$('toolbar').onclick=e=>{const b=e.target.closest('[data-format]');if(!b)return;const t=$('editor').value.slice($('editor').selectionStart,$('editor').selectionEnd)||'текст';const map={heading:'## '+t,bold:'**'+t+'**',italic:'*'+t+'*',list:'\n- '+t,number:'\n1. '+t,check:'\n- [ ] '+t,quote:'\n> '+t,link:'['+t+'](https://example.com)',wiki:'[['+t+']]',code:'`'+t+'`',block:'\n```\n'+t+'\n```\n',table:'\n| Название | Значение |\n| --- | --- |\n| Пример | Текст |\n',rule:'\n\n---\n\n'};insert(map[b.dataset.format])};
async function addPictures(files){if(!note()||note().deleted)return;for(const f of files){if(!['image/png','image/jpeg','image/gif'].includes(f.type)){toast('Поддерживаются PNG, JPEG и GIF.');continue}const ext={'image/png':'png','image/jpeg':'jpg','image/gif':'gif'}[f.type],key='attachments/'+uid()+'-'+safeName(f.name.replace(/\.[^.]*$/,'')).replace(/[^a-zA-Z0-9._-]/g,'_')+'.'+ext;try{await tx('attachments','readwrite',s=>s.put(f,key));const alt=prompt('Описание картинки',f.name)||'Фото';insert('\n!['+alt.replace(/[\[\]\n]/g,'')+']('+key+')\n')}catch(e){storageError(e);toast('Картинка не добавлена: запись не удалась. Оригинал не изменён.')}}}
$('image').onclick=()=>$('pictures').click();$('pictures').onchange=async()=>{await addPictures($('pictures').files);$('pictures').value=''};
$('editor').ondragover=e=>e.preventDefault();$('editor').ondrop=e=>{if(e.dataTransfer.files.length){e.preventDefault();addPictures(e.dataTransfer.files)}};$('editor').onpaste=e=>{const files=Array.from(e.clipboardData.items).filter(i=>i.kind==='file').map(i=>i.getAsFile());if(files.length){e.preventDefault();addPictures(files)}};
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='Изменения не сохранены'}});
function imageRefs(text){return Array.from(text.matchAll(/!\[[^\]]*\]\(\s*([^\s)]+)(?:\s+"[^"]*")?\s*\)/g),m=>m[1])}
function exportText(n){const prefix='../'.repeat(n.folder?n.folder.split('/').length:0);return n.text.replace(/(!\[[^\]]*\]\(\s*)([^\s)]+)/g,(all,start,src)=>{const key=attachmentKey(src,n);return key?start+prefix+key:all})}
function noteFilename(n){return (n.folder?n.folder.split('/').map(safeName).join('/')+'/':'')+safeName(n.title)+'.md'}
async function collectFiles(selected){const files=new Map(),attachments=new Set();for(const n of selected){let name=noteFilename(n);if(files.has(name))name=name.replace(/\.md$/,'-'+n.id+'.md');files.set(name,exportText(n));for(const src of imageRefs(n.text)){const key=attachmentKey(src,n);if(key)attachments.add(key)}}for(const key of attachments){const blob=await tx('attachments','readonly',s=>s.get(key));if(!blob)throw new Error('Вложение отсутствует: '+key);files.set(key,blob)}return files}
function download(blob,name){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),30000)}
async function zipDownload(files,name){const zip=new JSZip();for(const [p,v] of files)zip.file(p,v);const blob=await zip.generateAsync({type:'blob',compression:'STORE'});download(blob,name)}
async function backup(){const files=await collectFiles(state.notes);const keys=await tx('attachments','readonly',s=>s.getAllKeys());for(const key of keys)if(!files.has(key))files.set(key,await tx('attachments','readonly',s=>s.get(key)));files.set('backup.json',JSON.stringify({format:'quiet-notes-backup',version:1,state},null,2));await zipDownload(files,'Тихие-заметки-резервная-копия.zip')}
async function guard(fn){try{await fn()}catch(e){toast('Ошибка: '+e.message);console.error(e)}}
$('export').onclick=()=>{showDialog('Экспорт','<p>Markdown содержит ссылки на картинки, но не сами картинки. Для передачи вместе с фотографиями выберите ZIP.</p><div id="exports"></div><p><small>Резервная копия включает корзину, теги, избранное, папки и настройки. Сохраните её в надёжное место.</small></p>');const actions=[['Скачать заметку .md',()=>download(new Blob([note().text.replace(/(!\[[^\]]*\]\(\s*)([^\s)]+)/g,(all,start,src)=>{const key=attachmentKey(src,note());return key?start+key:all})],{type:'text/markdown;charset=utf-8'}),safeName(note().title)+'.md')],['Скачать .txt',()=>download(new Blob([note().text],{type:'text/plain;charset=utf-8'}),safeName(note().title)+'.txt')],['Скачать заметку с картинками',async()=>zipDownload(await collectFiles([note()]),safeName(note().title)+'.zip')],['Скачать все заметки',async()=>zipDownload(await collectFiles(live()),'Мои-заметки.zip')],['Резервная копия',backup],['Печать / PDF',()=>{$('dialog').close();mode('view');window.print()}]];for(const [label,fn] of actions){const b=document.createElement('button');b.textContent=label;b.onclick=()=>guard(fn);if(!note()&&!['Скачать все заметки','Резервная копия'].includes(label))b.disabled=true;$('exports').appendChild(b)}};
function validPath(p){return typeof p==='string'&&p.length<500&&!p.startsWith('/')&&!p.includes('\\')&&!p.includes('\0')&&!/^[a-z]:/i.test(p)&&p.split('/').every(x=>x!=='.'&&x!=='..'&&x.length>0)}
function validateBackup(data){if(!data||data.format!=='quiet-notes-backup'||data.version!==1)throw new Error('Неизвестный формат резервной копии');const s=data.state;if(!s||!Array.isArray(s.notes)||!Array.isArray(s.folders)||s.notes.length>10000)throw new Error('Неверная структура заметок');const ids=new Set();for(const n of s.notes){if(!n||typeof n.id!=='string'||ids.has(n.id)||typeof n.title!=='string'||!n.title||safeName(n.title)!==n.title||typeof n.text!=='string'||typeof n.folder!=='string'||n.folder&&!validPath(n.folder)||!Array.isArray(n.tags)||!n.tags.every(t=>typeof t==='string')||typeof n.favorite!=='boolean'||typeof n.deleted!=='boolean'||!Number.isFinite(n.modified))throw new Error('Повреждённая заметка в резервной копии');ids.add(n.id)}if(!s.folders.every(f=>typeof f==='string'&&validPath(f)&&f.split('/').every(p=>safeName(p)===p)))throw new Error('Повреждённые папки');for(const n of s.notes)if(n.folder&&!s.folders.includes(n.folder))throw new Error('Папка заметки отсутствует');const settings=s.settings||{};s.settings={theme:settings.theme==='dark'?'dark':'light',font:[14,16,18,20,24].includes(settings.font)?settings.font:16,mode:['edit','view','split'].includes(settings.mode)?settings.mode:'split'};return s}
async function commitImport(next,blobs,replace){if(saving){await new Promise(r=>setTimeout(r,100));return commitImport(next,blobs,replace)}await new Promise((resolve,reject)=>{const t=db.transaction(['state','attachments'],'readwrite');if(replace)t.objectStore('attachments').clear();for(const [key,blob] of blobs)t.objectStore('attachments').put(blob,key);t.objectStore('state').put(next,'vault');t.oncomplete=resolve;t.onerror=()=>reject(t.error);t.onabort=()=>reject(t.error||new Error('Импорт прерван'))});state=next;dirty=false;revision++;clearTimeout(saveTimer);folders();applySettings();select(live()[0]?.id||state.notes[0]?.id);$('status').textContent='Импорт сохранён';toast('Импорт завершён')}
async function importZip(file){if(file.size>100*1024*1024)throw new Error('Архив больше 100 МБ. Разделите его на части.');const zip=await JSZip.loadAsync(file,{checkCRC32:false,createFolders:false});const entries=Object.values(zip.files).filter(f=>!f.dir);if(entries.length>10000)throw new Error('Слишком много файлов');for(const entry of entries){if(!validPath(entry.name)||entry.unsafeOriginalName&&entry.unsafeOriginalName!==entry.name)throw new Error('Небезопасный путь в архиве')}if(entries.reduce((sum,e)=>sum+(e._data&&e._data.uncompressedSize||0),0)>250*1024*1024)throw new Error('Распакованный архив больше 250 МБ');await JSZip.loadAsync(file,{checkCRC32:true,createFolders:false});let total=0;const bytes=new Map();for(const entry of entries){const buf=await entry.async('uint8array');total+=buf.length;if(total>250*1024*1024)throw new Error('Распакованный архив больше 250 МБ');bytes.set(entry.name,buf)}const decoder=new TextDecoder('utf-8',{fatal:true});
if(bytes.has('backup.json')){const next=validateBackup(JSON.parse(decoder.decode(bytes.get('backup.json'))));const blobs=new Map();for(const [p,buf] of bytes)if(/^attachments\/[a-zA-Z0-9._-]+$/.test(p)){const mime=mimeFor(p);if(!mime)throw new Error('Неподдерживаемое вложение');blobs.set(p,new Blob([buf],{type:mime}))}for(const n of next.notes)for(const src of imageRefs(n.text)){const key=attachmentKey(src,n);if(key&&!blobs.has(key))throw new Error('В резервной копии отсутствует '+key)}if(!confirm('Восстановление ЗАМЕНИТ все текущие заметки, корзину и вложения. Сначала сохраните резервную копию. Продолжить?'))return;await commitImport(next,blobs,true);return}
const incoming=Array.from(bytes.keys()).filter(p=>/\.(md|txt)$/i.test(p)&&p!=='ИНСТРУКЦИЯ.md');if(!incoming.length)throw new Error('В архиве нет заметок .md или .txt');if(!confirm('Добавить '+incoming.length+' заметок? Существующие заметки не будут заменены; совпадающие имена получат суффикс.'))return;const next=JSON.parse(JSON.stringify(state)),blobs=new Map(),mapping=new Map();for(const [p,buf] of bytes){const mime=mimeFor(p);if(mime){const key='attachments/'+uid()+'.'+p.split('.').pop().toLowerCase();mapping.set(p,key);blobs.set(key,new Blob([buf],{type:mime}))}}
const titleMap=new Map();for(const p of incoming){const parts=p.split('/'),filename=parts.pop();const folder=parts.map(safeName).join('/');if(folder&&!next.folders.includes(folder))next.folders.push(folder);let title=safeName(filename.replace(/\.(md|txt)$/i,''));while(next.notes.some(n=>!n.deleted&&n.folder===folder&&n.title===title))title+=' (импорт)';const original=p.replace(/\.(md|txt)$/i,'');titleMap.set(original,(folder?folder+'/':'')+title);let text=decoder.decode(bytes.get(p));text=text.replace(/(!\[[^\]]*\]\(\s*)([^\s)]+)/g,(all,start,src)=>{if(/^[a-z]+:|^\/\//i.test(src))return all;let decoded;try{decoded=decodeURIComponent(src)}catch{return all}const stack=p.split('/').slice(0,-1);for(const bit of decoded.split('/')){if(bit==='..')stack.pop();else if(bit!=='.')stack.push(bit)}const key=mapping.get(stack.join('/'));return key?start+key:all});next.notes.push({id:uid(),title,folder,text,tags:[],favorite:false,deleted:false,modified:Date.now(),_original:original})}
for(const n of next.notes.filter(n=>n._original)){n.text=n.text.replace(/\[\[([^\]\n]+)\]\]/g,(all,inside)=>{const pieces=inside.split('|'),target=pieces[0].replace(/\.md$/i,'').trim();let translated=titleMap.get(target);if(!translated){const folder=n._original.split('/').slice(0,-1).join('/');translated=titleMap.get((folder?folder+'/':'')+target)}return translated?'[['+translated+(pieces.length>1?'|'+pieces.slice(1).join('|'):'')+']]':all});delete n._original}await commitImport(next,blobs,false)}
function mimeFor(p){return /\.png$/i.test(p)?'image/png':/\.jpe?g$/i.test(p)?'image/jpeg':/\.gif$/i.test(p)?'image/gif':null}
$('import').onclick=()=>$('files').click();$('files').onchange=()=>guard(async()=>{for(const f of $('files').files){if(/\.zip$/i.test(f.name)){await importZip(f);continue}if(!/\.(md|txt)$/i.test(f.name)){toast('Выберите .md, .txt или .zip');continue}if(f.size>10*1024*1024)throw new Error('Текстовый файл больше 10 МБ');const text=new TextDecoder('utf-8',{fatal:true}).decode(await f.arrayBuffer());let title=safeName(f.name.replace(/\.(md|txt)$/i,''));while(live().some(n=>n.title===title&&!n.folder))title+=' (импорт)';const n=makeNote(title,'',text);changed();select(n.id)}$('files').value=''});
$('ai').onclick=()=>{showDialog('Подготовка для нейросети','<p>Выберите заметки. Ссылка в Markdown не передаёт саму фотографию: загрузите и вложения. Поддержка ZIP зависит от сервиса. Данные никуда не отправляются.</p><div id="aiNotes"></div><label><input type="checkbox" id="linked">Включить связанные заметки</label><label><input type="checkbox" id="merged">Объединить в один Markdown внутри ZIP</label><button id="aiReview">Показать итоговый список файлов</button><div id="aiFiles"></div>');for(const n of live()){const label=document.createElement('label'),c=document.createElement('input');c.type='checkbox';c.value=n.id;c.checked=n.id===current;label.append(c,document.createTextNode(path(n)));$('aiNotes').append(label)}$('aiReview').onclick=()=>guard(async()=>{const ids=new Set(Array.from($('aiNotes').querySelectorAll('input:checked'),c=>c.value));if(!ids.size)throw new Error('Выберите хотя бы одну заметку');if($('linked').checked){let old;do{old=ids.size;for(const n of live().filter(n=>ids.has(n.id)))for(const r of wikiRefs(n.text))for(const target of resolve(r,n))ids.add(target.id)}while(ids.size!==old)}const selected=live().filter(n=>ids.has(n.id));const files=await collectFiles(selected);if($('merged').checked){for(const [p] of files)if(/\.md$/i.test(p))files.delete(p);files.set('Объединённые заметки.md',selected.map(n=>'# '+path(n)+'\n\n'+n.text.replace(/(!\[[^\]]*\]\(\s*)([^\s)]+)/g,(all,start,src)=>{const key=attachmentKey(src,n);return key?start+key:all})).join('\n\n---\n\n'))}files.set('ИНСТРУКЦИЯ.md','# Материалы для нейросети\n\nMarkdown-файлы содержат заметки. Папка attachments содержит исходные фотографии. Загрузите изображения отдельно, если сервис не умеет читать ZIP. Ссылки [[...]] обозначают другие заметки.\n');$('aiFiles').replaceChildren();const hint=document.createElement('p');hint.textContent='Итоговый список. Можно исключить лишнее; при исключении картинки её ссылка останется в тексте.';$('aiFiles').append(hint);for(const [p] of files){const l=document.createElement('label'),c=document.createElement('input');c.type='checkbox';c.checked=true;c.value=p;l.append(c,document.createTextNode(p));$('aiFiles').append(l)}const b=document.createElement('button');b.textContent='Скачать ZIP для нейросети';b.onclick=()=>guard(async()=>{const chosen=new Map();for(const c of $('aiFiles').querySelectorAll('input:checked'))chosen.set(c.value,files.get(c.value));if(!chosen.size)throw new Error('Список файлов пуст');await zipDownload(chosen,'Материалы-для-нейросети.zip')});$('aiFiles').append(b)})};
$('help').onclick=()=>showDialog('Как пользоваться','<ol><li>Нажмите «＋ Заметка» и введите название. Пишите в редакторе: изменения сохраняются автоматически.</li><li>Кнопка «Фото» добавляет PNG, JPEG или GIF. Также можно перетащить файл или вставить картинку из буфера.</li><li>Связывайте заметки: <code>[[Название]]</code> или <code>[[Папка/Название]]</code>. Откройте ссылку в просмотре.</li><li>Через «Экспорт» скачивайте заметки или резервную копию. Через «Импорт» открывайте .md, .txt, ZIP и восстанавливайте резервную копию.</li><li>«Для нейросети» позволяет выбрать заметки и проверить список файлов.</li></ol><p>После распаковки комплекта откройте index.html двойным щелчком. Не переносите папку приложения без резервной копии: хранилище привязано к браузеру и адресу файла. Не используйте режим инкогнито для постоянного хранения.</p><p>Изображения из интернета показываются только после вашего разрешения. Никаких аккаунтов и API-ключей не требуется. Безопаснее держать заметки меньше нескольких мегабайт, а большие коллекции фотографий регулярно архивировать.</p><p>В узком окне режим «Редактор + просмотр» показывает редактор; нажмите «Просмотр», чтобы увидеть результат. PDF сохраняется через диалог печати браузера.</p><p>Проверено в Chromium на Linux. Windows 10 32-бит и Яндекс 25.6.0.2372 требуют проверки на вашем компьютере. Если сохранение недоступно, экспортируйте текущие данные и не закрывайте страницу.</p>');
async function init(){try{if(!window.indexedDB)throw new Error('IndexedDB не поддерживается');db=await new Promise((resolve,reject)=>{const req=indexedDB.open('quiet-notes-v1',1);req.onupgradeneeded=()=>{req.result.createObjectStore('state');req.result.createObjectStore('attachments')};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);req.onblocked=()=>toast('Закройте другие окна приложения для открытия хранилища')});db.onversionchange=()=>{db.close();storageError(new Error('Хранилище изменено другим окном'))};const stored=await tx('state','readonly',s=>s.get('vault'));if(stored)state=stored;else{state.notes.push({id:uid(),title:'Добро пожаловать',folder:'',text:'# Ваше тихое место для мыслей\n\nЗаметки работают **без интернета** и остаются в вашем браузере.\n\n## Попробуйте\n\n- [ ] Создать первую заметку\n- [ ] Добавить фотографию\n- [ ] Скачать резервную копию\n\nПерейдите к [[Первая идея]].\n\n> Один небольшой шаг каждый день.\n\n| Возможность | Где найти |\n| --- | --- |\n| Фото | Кнопка сверху |\n| ZIP и резервная копия | Экспорт |\n\n```text\nЗдесь можно хранить примеры кода.\n```\n',tags:['начало'],favorite:true,modified:Date.now(),deleted:false});makeNote('Первая идея','','# Первая идея\n\nНапишите здесь свою мысль.\n\nВернуться: [[Добро пожаловать]].');changed();await persist()}ready=true;folders();applySettings();select(live()[0]?.id||state.notes[0]?.id)}catch(e){state.notes.push({id:uid(),title:'Несохранённая заметка',folder:'',text:'',tags:[],favorite:false,modified:Date.now(),deleted:false});folders();applySettings();select(state.notes[0].id);storageError(e)}}
// Prevent two windows from silently overwriting one another's local vault.
if(navigator.locks){navigator.locks.request('quiet-notes-single-writer',{ifAvailable:true},async lock=>{if(!lock){document.querySelectorAll('button,input,select,textarea').forEach(el=>el.disabled=true);toast('Приложение уже открыто в другом окне. Используйте его или закройте и обновите эту страницу.');$('status').textContent='Открыто в другом окне';return}await init();await new Promise(()=>{})}).catch(()=>{toast('Блокировка окон недоступна. Держите приложение открытым только в одном окне.');init()})}else init();
