const {chromium}=require('playwright');const assert=require('node:assert/strict');const fs=require('node:fs/promises');const JSZip=require('../vendor/jszip.min.js');
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',args:['--no-sandbox']});const ctx=await browser.newContext({acceptDownloads:true});const p=await ctx.newPage();p.on('dialog',d=>d.type()==='prompt'?d.accept('Новая'):d.accept());const requests=[];p.on('request',r=>{if(/^https?:/.test(r.url())&&!r.url().startsWith(process.env.QUIET_NOTES_TEST_URL+'/'))requests.push(r.url())});await p.goto(process.env.QUIET_NOTES_TEST_URL+'/index.html');await p.waitForSelector('#notes button');
const z=new JSZip();z.file('Проект/Вложенная/Фото.md','# Проверка\n\n![Фото](../../attachments/test.png)\n\n[[Проект/Связь]]');z.file('Проект/Связь.md','# Связь');z.file('attachments/test.png',Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jQxkAAAAASUVORK5CYII=','base64'));await p.setInputFiles('#files',{name:'notes.zip',mimeType:'application/zip',buffer:await z.generateAsync({type:'nodebuffer'})});await p.waitForFunction(()=>document.getElementById('notes').children.length===4);await p.getByRole('button',{name:'Фото',exact:false}).filter({has:p.locator('small')}).click();await p.waitForFunction(()=>document.querySelector('#preview img[src^="blob:"]'));assert((await p.locator('#editor').inputValue()).includes('](attachments/'));
await p.fill('#tags','проект, важное');await p.locator('#tags').press('Tab');await p.click('#star');await p.selectOption('#filter','favorite');assert.equal(await p.locator('#notes button').count(),2);await p.fill('#tagFilter','важное');assert.equal(await p.locator('#notes button').count(),1);await p.fill('#search','Проверка');assert.equal(await p.locator('#notes button').count(),1);await p.fill('#search','не найдено');assert.equal(await p.locator('#notes button').count(),0);await p.fill('#search','');await p.fill('#tagFilter','');await p.selectOption('#filter','all');await p.selectOption('#sort','title');
await p.click('#delete');await p.selectOption('#filter','trash');assert.equal(await p.locator('#notes button').count(),1);await p.click('#delete');await p.selectOption('#filter','all');assert.equal(await p.locator('#notes button').count(),4);
await p.click('#ai');assert.equal(await p.isChecked('#linked'),false);await p.check('#linked');await p.click('#aiReview');await p.waitForSelector('#aiFiles input');let dPromise=p.waitForEvent('download');await p.getByRole('button',{name:'Скачать ZIP для нейросети'}).click();let d=await dPromise,zip=await JSZip.loadAsync(await fs.readFile(await d.path()));assert(zip.file('Проект/Вложенная/Фото.md'));assert(zip.file('Проект/Связь.md'));assert(zip.file('ИНСТРУКЦИЯ.md'));assert(Object.keys(zip.files).some(x=>x.startsWith('attachments/')&&!zip.files[x].dir));await p.click('#closeDialog');
// Malicious archive and missing attachments must leave the previous vault intact.
const bad=new JSZip();bad.file('../evil.md','evil');await p.setInputFiles('#files',{name:'bad.zip',mimeType:'application/zip',buffer:await bad.generateAsync({type:'nodebuffer'})});await p.waitForFunction(()=>document.getElementById('toast').textContent.includes('Небезопасный'));assert.equal(await p.locator('#notes button').count(),4);
const other=await ctx.newPage();await other.goto(process.env.QUIET_NOTES_TEST_URL+'/index.html');await other.waitForFunction(()=>document.getElementById('status').textContent.includes('другом окне'));assert.equal(await other.isDisabled('#new'),true);await other.close();
await p.click('#theme');await p.selectOption('#font','18');await p.fill('#editor','# Тест интерфейса\n\nПростой текст, **выделение**, список:\n\n- Первый пункт\n- Второй пункт');await p.waitForTimeout(700);await p.screenshot({path:require('node:path').join(require('node:os').tmpdir(),'quiet-notes-desktop.png'),fullPage:true});await p.setViewportSize({width:390,height:844});await p.getByRole('button',{name:'Просмотр',exact:true}).click();await p.screenshot({path:require('node:path').join(require('node:os').tmpdir(),'quiet-notes-mobile.png'),fullPage:true});assert.equal(requests.length,0);await browser.close();console.log('PASS: nested ZIP import + images, tags, favorites, content search, sorting control, trash restore, related-note ZIP export, unsafe archive rejection, single-writer lock, theme/font/mobile preview, no external requests')})().catch(e=>{console.error(e);process.exit(1)});
