const {chromium}=require('playwright');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',args:['--no-sandbox']});const context=await browser.newContext();const p=await context.newPage();const errors=[],requests=[];p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(/^https?:/.test(r.url())&&!r.url().startsWith(process.env.QUIET_NOTES_TEST_URL+'/'))requests.push(r.url())});await p.goto(process.env.QUIET_NOTES_TEST_URL+'/index.html');await p.waitForSelector('#notes button');assert.equal(await p.title(),'Лист — место для мыслей');assert.equal(await p.locator('body').evaluate(el=>el.classList.contains('light')),false);assert.equal(await p.locator('#sort,#filter,#folderFilter,#tagFilter').count(),0);
// All resources already loaded. Prove spelling continues working with no network.
await context.setOffline(true);const e=p.locator('#editor');await e.fill('');await e.pressSequentially('Привте севодня пожалуста ');assert.equal(await e.inputValue(),'Привет сегодня пожалуйста ');await p.click('#undoCorrection');assert.equal(await e.inputValue(),'Привет сегодня пожалуста ');await e.fill('');await e.pressSequentially('сахранить ');assert.equal(await e.inputValue(),'сохранить ');await e.press('Control+z');assert.equal(await e.inputValue(),'сахранить ');
await e.fill('');await e.pressSequentially('карандашь');await p.waitForFunction(()=>document.getElementById('spellSuggestions').textContent.includes('карандаш'));await p.getByRole('button',{name:'карандаш',exact:true}).click();assert.equal(await e.inputValue(),'карандаш');await p.waitForFunction(()=>document.getElementById('status').textContent==='Сохранено в браузере');
for(const text of ['Привет привет странно', '```\n', '`', '[[', '![Фото](attachments/', 'https://example.com/', '#', '    ']){await e.fill(text);await e.pressSequentially('привте ');assert.equal(await e.inputValue(),text+'привте ')}
await e.fill('');await e.pressSequentially('Кузьмич нейроквантум ');assert.equal(await e.inputValue(),'Кузьмич нейроквантум ');
await p.locator('#appMenu > summary').click();await p.uncheck('#autocorrect');await e.fill('');await e.pressSequentially('севодня ');assert.equal(await e.inputValue(),'севодня ');await p.waitForFunction(()=>document.getElementById('status').textContent==='Сохранено в браузере');await context.setOffline(false);await p.reload();await p.waitForSelector('#notes button');await p.locator('#appMenu > summary').click();assert.equal(await p.isChecked('#autocorrect'),false);await p.check('#autocorrect');await e.fill('');await e.pressSequentially('привте ');assert.equal(await e.inputValue(),'привет ');
await p.locator('#title').fill('Новая спокойная страница');await p.locator('#title').press('Tab');await e.fill('Иногда достаточно одного листа, чтобы всё стало яснее.\n\nСегодня я хочу записать идею, добавить фотографию и оставить место для нового.\n\n- Не торопиться\n- Замечать маленькие вещи\n- Сохранять то, что важно');await p.click('#editor');await p.waitForTimeout(600);await p.screenshot({path:require('node:path').join(require('node:os').tmpdir(),'list-desktop.png'),fullPage:true});await p.setViewportSize({width:390,height:844});await p.screenshot({path:require('node:path').join(require('node:os').tmpdir(),'list-mobile.png'),fullPage:true});
assert.deepEqual(errors,[]);assert.deepEqual(requests,[]);await browser.close();console.log('PASS: dark simplified UI, offline Russian auto-corrections, casing, undo button/Ctrl+Z, dictionary suggestions, code/link/file protection, unknown-word safety, disabled setting persisted, desktop/mobile UI')})().catch(e=>{console.error(e);process.exit(1)});
